// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rprvesldwwgotoqtuhrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwcnZlc2xkd3dnb3RvcXR1aHJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2Nzg0NjAsImV4cCI6MjA3MjI1NDQ2MH0.yZMW3s4nBuNtit87GLpwZLNHQ_a_3RBxuVgHLWSO27Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});